### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by leon-vv** [tylerlong/asciimath-to-latex#3]
Hello! Thanks for sharing this project.

Under which license is this software available?

Is it true that large parts of this software is based on [this code ](https://github.com/asciimath/asciimathml/blob/master/asciimath-based/ASCIIMathTeXImg.js)? In that case you should credit the original authors and include their license. It seems their code is [available under the MIT license](https://github.com/asciimath/asciimathml/issues/47#ref-pullrequest-144037568).

**Comment by tylerlong** [comment]
This project is also under MIT license. You can conclude that by reading package.json file.

MIT license doesn't require crediting the original author, does it? Correct me if I am wrong.

**Comment by leon-vv** [comment]
Thank you for answering. It looks like it's a bit of a gray area, but I think it's nice to credit the original authors.
