### ISSUE TITLE
How to use with module js?

### ISSUE THREAD

**Issue by igorcafe** [tylerlong/asciimath-to-latex#6]

**Comment by igorcafe** [comment]
I tried the regular `import asciimath2latex from 'asciimath-to-latex'`, but it didn't work so I tried out this way, and didn't work neither.

![image](https://user-images.githubusercontent.com/85039990/161451664-4530e1a6-6832-44e2-81eb-9827118044b2.png)

**Comment by igorcafe** [comment]
Actually it is not a ESM problem.
I tried the code sample at the README.md, but it does not work here...
And my package is commonjs now.

![image](https://user-images.githubusercontent.com/85039990/161451923-7693ab5d-ecb6-4b9a-9bda-7602cf82da4f.png)

**Comment by tylerlong** [comment]
Please check this demo project: https://github.com/tylerlong/asciimath-to-latex-demo

Either:

```js
import asciimath2latex from 'asciimath-to-latex'
```

or:

```js
const asciimath2latex = require('asciimath-to-latex').default
```
